version: '3.6'
services:
  backend:
    build: 
      context: ${backend_dir}
      dockerfile: Dockerfile.backend
    volumes:
      - ${backend_dir}:/mybudget-backend
    command: puma -p 4567
    ports:
      - "4567:4567"
  frontend:
    build: 
      context: ${frontend_dir}
      dockerfile: Dockerfile.frontend
    volumes:
      - ${frontend_dir}:/mybudget-frontend
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
